apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "python.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.targetport }} 
    nodePort: {{ .Values.service.nodeport }}
